name: 湘猿@hncoder
title: iOS攻城狮
description: 一枚「湘」籍程序「猿」的技术博客。
meta_description: "hncoder's blog"

github: hncoder
linkedin: hncoder
email: i@hncoder.com


markdown: kramdown
highlighter: rouge

paginate: 50
baseurl: /
domain_name: 'http://hncoder.com'
#google_analytics: 'UA-62842593-1'
disqus_shortname: 'hncoder'

# Details for the RSS feed generator
url:            'http://hncoder.com'
author:         'hncoder'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
