name: hncoder
title: 湘籍程序猿
description: Life is like an npm install.
meta_description: "hncoder's blog"


markdown: kramdown
highlighter: rouge

paginate: 50
baseurl: /
domain_name: 'http://hncoder.com'
#google_analytics: 'UA-62842593-1'
disqus_shortname: 'hncoder'

# Details for the RSS feed generator
url:            'http://hncoder.com'
author:         'hncoder'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
